# Default values for oracle-sharding-si-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# Copyright 2020, Oracle Corporation and/or affiliates.  All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl
# MAINTAINER <paramdeep.saini@oracle.com>
#
---
global:
  gsmimage:
   repository: phx.ocir.io/intsanjaysingh/db-repo/oracle/databse-gsm 
   tag: 19.3.0
   pullPolicy: IfNotPresent
  dbimage:
   repository: phx.ocir.io/intsanjaysingh/db-repo/oracle/database
   tag: 19.3.0-ee
   pullPolicy: IfNotPresent
  secret:
   oraclePwd: db-user-pass
   oraclePwdLoc: /mnt/secrets
  strategy: Recreate
  getScrCmd: "curl https://codeload.github.com/psaini79/db-sharding/tar.gz/master |   tar -xz --strip=4 db-sharding-master/docker-based-sharding-deployment/dockerfiles/19.3.0/scripts" 
  registrySecret: oshardsecret
  gsmports:
   containerGSMProtocol: TCP
   containerGSMPortName: oshardgsm-port
   containerGSMPort: 1521
   containerONSrPortName:  gsm-onsrport
   containerONSrPort: 6234
   containerONSlPortName:  gsm-onslport
   containerONSlPort: 6123
   containerAgentPortName:  gsm-agentport
   containerAgentPort: 8080
  dbports:
   containerDBProtocol: TCP
   containerDBPortName: db1-port
   containerDBPort: 1521
   containerONSrPortName:  db1-onsrport
   containerONSrPort: 6234
   containerONSlPortName:  db1-onslport
   containerONSlPort: 6123
   containerAgentPortName:  db1-agentport
   containerAgentPort: 8080
  service:
   type: LoadBalancer
   port: 1521

gsm:
  replicaCount: 1
  gsmHostName: gsmhost
  nodeselector: ad3
  oci:
   region: phx
   zone: PHX-AD-1
  pvc:
   ociAD: "PHX-AD-1"
   storageSize: 50Gi
   accessModes: ReadWriteOnce
   storageClassName: oci
   DBMountLoc: /u01/app/oracle/gsmdata 
   stagingLoc: /opt/oracle/gsm/scripts/setup
  service:
   type: LoadBalancer
   port: 1521
  env:
   SHARD_DIRECTOR_PARAMS: "director_name=sharddirector1;director_region=region1;director_port=1521"
   SHARD1_GROUP_PARAMS: "group_name=shardgroup1;deploy_as=primary;group_region=region1" 
   CATALOG_PARAMS: "catalog_host=oshard-catalog-0.oshard-catalog;catalog_db=CATCDB;catalog_pdb=CAT1PDB;catalog_port=1521;catalog_name=shardcatalog1;catalog_region=region1,region2"
   SHARD1_PARAMS: "shard_host=oshard1-0.oshard1;shard_db=ORCL1CDB;shard_pdb=ORCL1PDB;shard_port=1521;shard_group=shardgroup1"
   SHARD2_PARAMS: "shard_host=oshard2-0.oshard2;shard_db=ORCL2CDB;shard_pdb=ORCL2PDB;shard_port=1521;shard_group=shardgroup1"
   SHARD3_PARAMS: "shard_host=oshard3-0.oshard3;shard_db=ORCL3CDB;shard_pdb=ORCL3PDB;shard_port=1521;shard_group=shardgroup1" 
   SERVICE1_PARAMS: "service_name=oltp_rw_svc;service_role=primary"
   SERVICE2_PARAMS: "service_name=oltp_ro_svc;service_role=primary"
   BASE_DIR: /opt/oracle/gsm/scripts/setup
   COMMON_OS_PWD_FILE: common_os_pwdfile.enc
   PWD_KEY: pwd.key
   OP_TYPE: gsm  

oshard1:
  replicaCount: 1
  app: oshard-db1
  nodeselector: ad3
  shardHostName: oshard1
  storageType: "bv"
  oci:
   region: phx
   zone: PHX-AD-1
  pvc:
   ociAD: "PHX-AD-1"
   storageSize: 50Gi
   accessModes: ReadWriteOnce
   storageClassName: oci
   DBMountLoc: /opt/oracle/oradata
   stagingLoc: /opt/oracle/scripts/setup
  env:
   ORACLE_SID: ORCL1CDB
   ORACLE_PDB: ORCL1PDB
   OP_TYPE: primaryshard
   DB_MEMORY: 12G
   COMMON_OS_PWD_FILE: common_os_pwdfile.enc
   PWD_KEY: pwd.key
  clone:
   db: "no"
   ocid: 
  nfs:
   storageClassName: oci-fss
   mountOptions: nosuid
   serverName: xx.xx.xx.xx
   path: /shard_nfs

oshard2:
  replicaCount: 1
  app: oshard-db2
  nodeselector: ad3
  shardHostName: oshard2
  storageType: "bv"
  oci:
   region: phx
   zone: PHX-AD-1
  pvc:
   ociAD: "PHX-AD-1"
   storageSize: 50Gi
   accessModes: ReadWriteOnce
   storageClassName: oci
   DBMountLoc: /opt/oracle/oradata
   stagingLoc: /opt/oracle/scripts/setup
  env:
   ORACLE_SID: ORCL2CDB
   ORACLE_PDB: ORCL2PDB
   OP_TYPE: primaryshard
   DB_MEMORY: 12G
   COMMON_OS_PWD_FILE: common_os_pwdfile.enc
   PWD_KEY: pwd.key
  clone:
   db: "no"
   ocid: 
  nfs:
   storageClassName: oci-fss
   mountOptions: nosuid
   serverName: xx.xx.xx.xx
   path: /shard_nfs

oshard3:
  replicaCount: 1
  app: oshard-db3
  nodeselector: ad3
  shardHostName: oshard3
  storageType: "bv"
  oci:
   region: phx
   zone: PHX-AD-1
  pvc:
   ociAD: "PHX-AD-1"
   storageSize: 50Gi
   accessModes: ReadWriteOnce
   storageClassName: oci
   DBMountLoc: /opt/oracle/oradata
   stagingLoc: /opt/oracle/scripts/setup
  env:
   ORACLE_SID: ORCL3CDB
   ORACLE_PDB: ORCL3PDB
   OP_TYPE: primaryshard
   DB_MEMORY: 12G
   COMMON_OS_PWD_FILE: common_os_pwdfile.enc
   PWD_KEY: pwd.key
  clone:
   db: "no"
   ocid: 
  nfs:
   storageClassName: oci-fss
   mountOptions: nosuid
   serverName: xx.xx.xx.xx
   path: /shard_nfs

oshard-catalog:
  replicaCount: 1
  app: oshard-cat
  nodeselector: ad3
  shardHostName: oshard-catalog
  storageType: "bv"
  oci:
   region: phx
   zone: PHX-AD-1
  pvc:
   ociAD: "PHX-AD-1"
   storageSize: 50Gi
   accessModes: ReadWriteOnce
   storageClassName: oci
   DBMountLoc: /opt/oracle/oradata
   stagingLoc: /opt/oracle/scripts/setup
  env:
   ORACLE_SID: CATCDB
   ORACLE_PDB: CAT1PDB
   OP_TYPE: catalog
   DB_MEMORY: 12G
   COMMON_OS_PWD_FILE: common_os_pwdfile.enc
   PWD_KEY: pwd.key
  clone:
   db: "no"
   ocid: 
  nfs:
   storageClassName: oci-fss
   mountOptions: nosuid
   serverName: xx.xx.xx.xx
   path: /shard_nfs
